# Generated by Django 4.2.7 on 2023-12-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcompras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lcompras",
            name="setor",
            field=models.CharField(
                choices=[
                    ("Açougue", "Açougue"),
                    ("Bebidas", "Bebidas"),
                    ("Bomboniere", "Bomboniere"),
                    ("Conservas", "Conservas"),
                    ("Grãos", "Grãos"),
                    ("Limpeza", "Limpeza"),
                    ("Hortifruti", "Hortifruti"),
                    ("Lacticínios", "Lacticínios"),
                    ("Organizadores", "Organizadores"),
                    ("Padaria", "Padaria"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
