# Generated by Django 4.2.7 on 2023-12-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcompras", "0002_alter_lcompras_setor"),
    ]

    operations = [
        migrations.AddField(
            model_name="lcompras",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
