# Generated by Django 4.2.7 on 2023-12-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcompras", "0003_lcompras_observacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lcompras",
            name="codsetor",
        ),
        migrations.AlterField(
            model_name="lcompras",
            name="setor",
            field=models.CharField(
                choices=[
                    (1, "Açougue"),
                    (2, "Bebidas"),
                    (3, "Bomboniere"),
                    (4, "Conservas"),
                    (5, "Grãos"),
                    (6, "Limpeza"),
                    (7, "Hortifruti"),
                    (8, "Lacticínios"),
                    (9, "Organizadores"),
                    (10, "Padaria"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
