# Generated by Django 4.2.7 on 2023-12-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcompras", "0004_remove_lcompras_codsetor_alter_lcompras_setor"),
    ]

    operations = [
        migrations.AddField(
            model_name="lcompras",
            name="codsetor",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
