# Generated by Django 4.2.7 on 2023-12-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lcompras", "0007_setor_alter_lcompras_setor_lcompras_codsetor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lcompras",
            name="codsetor",
        ),
        migrations.DeleteModel(
            name="Setor",
        ),
    ]
