# Generated by Django 4.2.7 on 2023-12-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcompras", "0008_remove_lcompras_codsetor_delete_setor"),
    ]

    operations = [
        migrations.AddField(
            model_name="lcompras",
            name="codsetor",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
