# Generated by Django 4.2.7 on 2023-12-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcompras", "0011_alter_lcompras_codsetor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lcompras",
            name="codsetor",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=2
            ),
        ),
    ]
