# Generated by Django 4.2.7 on 2023-12-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcompras", "0014_alter_lcompras_setor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lcompras",
            name="setor",
            field=models.IntegerField(
                choices=[
                    ("Conservas", 1),
                    ("Graos", 2),
                    ("Bomboniere", 3),
                    ("Acougue", 4),
                    ("Limpeza", 5),
                    ("Organizadores", 6),
                    ("Hortifruti", 7),
                    ("Padaria", 8),
                    ("Laticinios", 9),
                    ("Bebidas", 10),
                ],
                default=1,
            ),
        ),
    ]
