# Generated by Django 4.2.7 on 2023-12-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtoimg",
            name="setor",
            field=models.CharField(max_length=15),
        ),
    ]
