# Generated by Django 4.2.7 on 2023-12-02 12:16
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_alter_produtoimg_setor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtoimg",
            name="setor",
            field=models.CharField(
                choices=[
                    ("Açougue", "Açougue"),
                    ("Bebidas", "Bebidas"),
                    ("Bomboniere", "Bomboniere"),
                    ("Conservas", "Conservas"),
                    ("Grãos", "Grãos"),
                    ("Limpeza", "Limpeza"),
                    ("Hortifruti", "Hortifruti"),
                    ("Laticínios", "Laticínios"),
                    ("Organizadores", "Organizadores"),
                    ("Padaria", "Padaria"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
