# Generated by Django 4.2.7 on 2023-12-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0006_alter_produtoimg_setor"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtoimg",
            name="codsetor",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
