# Generated by Django 4.2.7 on 2023-12-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0007_produtoimg_codsetor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtoimg",
            name="unidade",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
